### ISSUE TITLE
运行evaluate.py出现报错mypc.json

### ISSUE THREAD

**Issue by Aucy1** [fire717/movenet.pytorch#49]
我按照readme执行到训练完，开始测试时，执行python evaluate.py出现报错问题Traceback (most recent call last):
  File "evaluate.py", line 57, in <module>
    main(cfg)
  File "evaluate.py", line 28, in main
    data_loader = data.getEvalDataloader()
 File "/movenet.pytorch-master/lib/data/data.py", line 159, in getEvalDataloader
    with open(self.cfg['eval_label_path'], 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/eval/mypc.json'
我找了所有的文件夹都没有这个mypc.json文件

**Comment by fire717** [comment]
这个应该是要根据你自己的数据去生成的，生成方式和train一样。

**Comment by ajiancode** [comment]
请问后来这个问题解决了吗？

**Comment by wovhwhy** [comment]
同问
