### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [161, 48, 48] at entry 0 and [86, 48, 48] at entry 1

### ISSUE THREAD

**Issue by bobby20180331** [fire717/movenet.pytorch#7]
我生成了自己的新数据集（32点）。
然后参考以下做了数据集转换。
movenet.pytorch/scripts/make_coco_data_17keypoints.py
然后报了这个异常：
RuntimeError: stack expects each tensor to be equal size, but got [161, 48, 48] at entry 0 and [86, 48, 48] at entry 1
暂时没能解决，有解决的思路吗？

**Comment by bobby20180331** [comment]
origin message:
/data/ai/movenet.pytorch$ python train.py 
/data/anaconda3/envs/py397/lib/python3.9/site-packages/torch/nn/_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
--------------------------------------------------
{'GPU_ID': '0', 'num_workers': 8, 'random_seed': 42, 'cfg_verbose': True, 'save_dir': 'output/', 'num_classes': 32, 'width_mult': 1.0, 'img_size': 192, 'img_path': './data/croped/imgs', 'train_label_path': './data/croped/32kp-train.json', 'val_label_path': './data/croped/32kp-val.json', 'balance_data': False, 'log_interval': 10, 'save_best_only': True, 'pin_memory': True, 'learning_rate': 0.001, 'batch_size': 64, 'epochs': 200, 'optimizer': 'Adam', 'scheduler': 'MultiStepLR-70,100-0.1', 'weight_decay': 0.0005, 'class_weight': None, 'clip_gradient': 5, 'test_img_path': './data/croped/test', 'exam_label_path': './data/croped/kp-movenet-test.json', 'eval_img_path': './data/croped/test', 'eval_label_path': '../data/eval/kp-movenet-test.json'}
--------------------------------------------------
[INFO] Total train images: 1689, val images: 185
[INFO] Not do data balance.
Traceback (most recent call last):
  File "/data/ai/movenet.pytorch/train.py", line 32, in <module>
    main(cfg)
  File "/data/ai/movenet.pytorch/train.py", line 29, in main
    run_task.train(train_loader, val_loader)
  File "/data/ai/movenet.pytorch/lib/task/task.py", line 52, in train
    self.onTrainStep(train_loader, epoch)



Original Traceback (most recent call last):
  File "/data/anaconda3/envs/py397/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/anaconda3/envs/py397/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)
  File "/data/anaconda3/envs/py397/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 84, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/data/anaconda3/envs/py397/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 84, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/data/anaconda3/envs/py397/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/data/anaconda3/envs/py397/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 56, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [161, 48, 48] at entry 0 and [86, 48, 48] at entry 1

**Comment by fire717** [comment]
原始模型结构是默认17点的，如果你是32点，需要相应修改模型结构

**Comment by bobby20180331** [comment]
谢谢指点，已经修改，能够工作了。
修改了三处：
1.程序里关于图像增强-左右镜像部分需要修改，
2. 有两处movenetdecode...要带参数调用
